validate:
	terraform fmt
	terraform init
	terraform validate 
	
plan:
	terraform plan

auto_apply:
	terraform apply -auto-approve

planout:
	terraform plan -out=out.plan

apply:
	terraform apply out.plan
